### ISSUE TITLE
Updated html2text upstream location in Debian

### ISSUE THREAD

**Issue by hosiet** [grobian/html2text#1]
Dear new html2text developer,

Thanks for migrating this project onto GitHub. I just made a maintenance update for Debian's html2text package to indicate that the new upstream is on GitHub.

The html2text package in Debian is currently orphaned, i.e., no one is actively maintaining it in Debian currently. I may take a look at it but there's no guarantee.

I see that there hasn't been any releases for the new html2text. Once you make a new release, please consider properly tagging it (using `git tag`) so that it shows up on https://github.com/grobian/html2text/releases and https://github.com/grobian/html2text/tags . After that, Debian's monitoring system will know that a new upstream release is available. You may also directly poke me if necessary.

**Comment by grobian** [comment]
A release is planned soon, but I'm trying to sort out some issues I still see with the current additions/modifications in development.

Thanks!

**Comment by h01ger** [comment]
a release would be great. I might pick up the package again... (part of the reasons to drop it was lack of upstream activity...)
