### ISSUE TITLE
Failing to parse this URL?

### ISSUE THREAD

**Issue by youradds** [grobian/html2text#15]
Using the latest version, it seems to fail on quite a few domains. For example:

[pylopic.com.txt](https://github.com/grobian/html2text/files/6615338/pylopic.com.txt)

Using:

`/usr/local/bin/html2text -nobs pylopic.com.txt`

There are no errors, but its a 0 byte file

**Comment by grobian** [comment]
I can confirm that nothing appears to happen, running -debug_parser shows it is processing a lot of elements though

**Comment by youradds** [comment]
Thanks for looking. I think part of the problem was with the <v-style> stuff on that page messing up the Perl module HTML::Restrict, which I use to remove dud content we don't want to store (styles, css, js, etc). 

Before parsing, I've now replaced it with normal <style>, and then it seems to do the trick of getting rid of those tags without screwing up the outputted HTML. Then, when putting through html2text, it works :)

**Comment by grobian** [comment]
I've no idea what to do here, closing, please reopen if there is something to fix here
