### ISSUE TITLE
missing HTML 4 entities

### ISSUE THREAD

**Issue by StevanWhite** [grobian/html2text#22]
Several SGML character entities are missing in sgml.cpp

Some of less use than others, but it is easy to complete the set, and it is lousy to output the name of a character to a console capapble of UTF-8
See https://www.w3.org/TR/html4/sgml/entities.html

NOTE there is one issue with the entity `&thetasym; ` A buffer of size 8 is insufficient to hold the string of that name.
The magic number 8 appears twice in sgml.cpp -- this value should be replaced by a named constant or something.
A value of 9 suffices to hold the name of any currently defined SGML entity.

BETTER use std::string for the entity names.

The following entries would complete the set, with that caveat.
```
        { "emsp",     0x2003 },
        { "ensp",     0x2002 },
        { "fnof",     0x0192 },
        { "frasl",    0x2044 },
        { "lrm",      0x200e },
        { "oline",    0x203e },
        { "rlm",      0x200f },
        { "sbquo",    0x201a },
        { "thetasym", 0x03D1 },
        { "thinsp",   0x2009 },
        { "upsih",    0x03D2 },
        { "zwj",      0x200D },
```

**Comment by grobian** [comment]
Would you be willing to create a PR for this?  I'd agree on a constant for the magical 8.

**Comment by StevanWhite** [comment]
I don't understand: is an "Issue" not a problem report?  Or is PR something other than problem report?

**Comment by grobian** [comment]
:)
in Git(*) speak PR means Pull-Request, e.g. I suggested you to create a patch (you did all the work already of figuring out what to do), which if you do that according to Git guidelines, I can "push" and basically record that you did the work (Git author).  That is, if you feel up for that, more than ok with just cooking it up myself, just wanted to give you the opportunity to own/get credit for your contributions.

**Comment by StevanWhite** [comment]
Yeah, I can do that.  I am a fairly good programmer.

Although I have been involved in GIT projects before, I am not great on GIT, and I'm pretty sure I don't want to be.  You'll have to tolerate and correct GIT foul-ups.  

I don't care about credit.  I just want a functioning tool, and I'm glad to help.

**Comment by grobian** [comment]
Whatever works for you.  You may also send a patch (no git w/e involved) to my email, I'll fixup/apply afterwards.  In any case, whatever you prefer works for me here.

**Comment by StevanWhite** [comment]
Please tell me what to do.  I looked at creating pull requests, and it seems I have to create something.  Last place I worked had a strict policy on naming whatevers and whatnots.  Do you have such a policy?

**Comment by grobian** [comment]
Oh, no, you just need to do git foo.  If your patch is small enough you can also produce a diff -u old new and paste it here.

**Comment by StevanWhite** [comment]
Please be explicit.  What exactly do I need to type? (--- to clone the repository?)  (I tried several things, nothing worked.)

**Comment by grobian** [comment]
easiest thing I can think of here is this:

% git clone https://github.com/grobian/html2text.git
% cd html2text
% ./configure
% vi/emacs/nano whatever-files
% make
% git diff > issue22.patch

you can repeat the edit make and git diff steps obviously as much as you like

**Comment by grobian** [comment]
I was trying to tell you that, all I need is a patch :)

**Comment by StevanWhite** [comment]
Hm.  All I heard was pull request git git git.  I assumed you wanted to use the version control system to do version control.

Here's your patch.

I also included a test file, taken from the standards.  Notice that none of the character entities is rendered verbatim
[sgml.cpp.patch.gz](https://github.com/grobian/html2text/files/8399528/sgml.cpp.patch.gz)
[entities.html.gz](https://github.com/grobian/html2text/files/8399529/entities.html.gz)
.

**Comment by StevanWhite** [comment]
Confirmed.
