### ISSUE TITLE
Older HTML charset specification not working

### ISSUE THREAD

**Issue by StevanWhite** [grobian/html2text#23]
In HTML prior to HTML 5, the usual way to indicate character encoding was a META tag in the HEAD, e.g.
`<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>`
This is still probably the method that occurs most commonly.
But it is not recognized with the current build.

**Comment by grobian** [comment]
hmmm, that's annoying, https://github.com/grobian/html2text/commit/f7913574870b41c89df0ca21592662c8616ec645 was supposed to address that

**Comment by grobian** [comment]
cruft, think I know what it is, got lost along the way of implementing its support

**Comment by StevanWhite** [comment]
Confirmed: encoding correctly identified with either the older or new meta tag.
