### ISSUE TITLE
build clean with warning messages enabled

### ISSUE THREAD

**Issue by StevanWhite** [grobian/html2text#24]
I have managed to make the thing build cleanly with standard warning messages enabled.
Mostly minor issues, but each is something that would raise questions to a developer reading the code.
I would like to provide you with those changes --- but this would be a many-file patch.

One issue I can't resolve is probably some kind of mistake: format.cpp, line 1232: I really hope it isn't functional.
Probably you want to comment out all that code, or else make it really do something.

How should we proceed?

**Comment by StevanWhite** [comment]
Hello?

**Comment by StevanWhite** [comment]
OK I see, you already got it going with `-Wall`.  Great!
I would also suggest` -Wextra`, for the same reason.  It turns up several little confusions.

I find it constraining to discuss things in these bug reports.  Even e-mail would be better.  A chat, maybe?  Does github have some better messaging facility?

**Comment by grobian** [comment]
yup, email is fine!

**Comment by grobian** [comment]
5914c0d718e277e2644592c90d5e7ed756a57c1d adds -Wextra

**Comment by StevanWhite** [comment]
Problem: how do we exchange e-mails, short of putting them on a public forum?

**Comment by grobian** [comment]
git show should reveal how you can reach me...
