### ISSUE TITLE
update GPL

### ISSUE THREAD

**Issue by StevanWhite** [grobian/html2text#25]
It is very desirable to update to GPL 3.0+.
For one thing, it will improve the product's acceptability to some distros.

I think this involves replacing the COPYING file, and the text banner at the top of the source files.
Any other references to the older license should go away.

[About GPL](https://www.gnu.org/licenses/licenses.html#GPL)
[GPL 3.0](https://www.gnu.org/licenses/gpl-3.0.html)

**Comment by grobian** [comment]
Hmmm, I need to check GPL-3.  Perhaps Apache-2 licence?

**Comment by StevanWhite** [comment]
You would have to check if it is permitted to switch a license from GPL to Apache.
The previous contributors all agreed to GPL, not Apache.

But why?  It's easy to update the GPL license.

**Comment by ryandesign** [comment]
It's already licensed "GPL 2 or later". Anyone wishing to use it under the terms of the GPL 3 can already do so.

**Comment by grobian** [comment]
Based on Ryan's comment, I'm not going to up the licence to GPL-3 at this point.  All files should be properly licenced now for "GPL-2 or later".
