### ISSUE TITLE
unparse functionality: unicode output

### ISSUE THREAD

**Issue by StevanWhite** [grobian/html2text#27]
With the -unparse flag,
Most Unicode characters come out wrong, like an empty character entity, like "`&#;`"

**Comment by grobian** [comment]
meta-question, what is unparse useful for?  Wouldn't it be a better idea to just kill unparse (and all the bugs about it)?  Strict/conformant parsing should never be the option, producing something useful would be (think like vilistextum and what giant software corporations produce in terms of crap which unfortunately send you email via their happy consumers).

**Comment by StevanWhite** [comment]
I don't use it, and I don't know who does.
And there is the `tidy` program, which does something like this already.

This is one of those things that might be too hard to justify a fix in the short term.
If you can fix it easily, sure.  If not.... your suggestion to remove the option seems reasonable.
