### ISSUE TITLE
unparse functionality: elements re-ordered badly

### ISSUE THREAD

**Issue by StevanWhite** [grobian/html2text#28]
With `-unparse` flag:

Elements in the `<HEAD>` are re-arranged, in a bad way.  

Specifically, `<STYLE>` tags are placed before `<META>` tags.  This could be very bad, as the `<STYLE>` could be arbitrarily long, and one of the `<META>` tags contains character encoding information, which should appear very near the beginning of the file.

I think this program should not re-order HTML elements at all.

**Comment by grobian** [comment]
this is because head is statically re-created in a set order, personally I don't find this important enough to be fixed

**Comment by StevanWhite** [comment]
The reason is: it will cause encoding detection of the output file to fail sometimes.
And as I said, there is no reason for this program to rearrange HTML elements.

But as we noted elsewhere, the `-unparse` functionality has been broken, since early versions.  
It could only be used in very limited circumstances --- and I can't imagine what circumstances.
