### ISSUE TITLE
error: private field 'yylval' is not used

### ISSUE THREAD

**Issue by ryandesign** [grobian/html2text#38]
Now that you've added `-Werror` to the CXXFLAGS this warning is an error:
```
In file included from HTMLDriver.cpp:14:
./HTMLDriver.h:50:41: error: private field 'yylval' is not used [-Werror,-Wunused-private-field]
                html2text::HTMLParser::semantic_type *yylval = nullptr;
                                                      ^
1 error generated.
```
I recommend not including `-Werror` in the standard CXXFLAGS because new compilers have a tendency to introduce new warnings which break old build systems. In this way, build systems with `-Werror` are a ticking time bomb just waiting to create work for those who maintain packages in package management systems.

**Comment by grobian** [comment]
Right I hate -Werror too.  Let's kill it.  It should only be used by developers IMO.
