### ISSUE TITLE
GPL license incompatibilities

### ISSUE THREAD

**Issue by ryandesign** [grobian/html2text#39]
html2text claims to be licensed under the GPL-2 or later however my MacPorts colleague @jmroot [pointed out](https://github.com/macports/macports-ports/commit/84464232cbe1880584794959dd58cbfcfd801788) that some of the files contain additional wording that is contradictory to the GPL. For example html.h says:

```
/*
 * Portions Copyright (c) 1999 GMRS Software GmbH
 * Carl-von-Linde-Str. 38, D-85716 Unterschleissheim, http://www.gmrs.de
 * All rights reserved.
 *
 * Author: Arno Unkrig <arno@unkrig.de>
 *
 * All advertising materials mentioning features or use of this software
 * must display the following acknowledgement:
 * "This product includes software developed by GMRS Software GmbH."
 * The name of GMRS Software GmbH may not be used to endorse or promote
 * products derived from this software without specific prior written
 * permission.
 */

/* This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License in the file COPYING for more details.
 */
```

The [full text of the GPL](https://github.com/grobian/html2text/blob/master/COPYING) of course says "You may not impose any further restrictions on the recipients' exercise of the rights granted herein." But the above "All advertising materials mentioning features or use of this software must display the following acknowledgement" is a further restriction and therefore incompatible with the GPL.

I understand from the [email exchange quoted in the readme](https://github.com/grobian/html2text/blob/master/README-1.3.2a#L93-L109) that the original author(s) agreed to relicense under the GPL, which to my mind would mean that the advertising/endorsement paragraph above would have to be removed, otherwise this software isn't actually licensed under the GPL. What the email said exactly was:

> html2text darf unter die GPL veroeffentlicht werden, solange one4net keinerlei Nachteile oder Verpflichtungen dadurch entstehen

My translation:

> html2text can be released under the GPL as long as no disadvantages or obligations whatsoever arise for one4net as a result

Perhaps one needs to clarify with the original authors whether they see the loss of the incompatible advertising/endorsement paragraph as a disadvantage or obligation.

There was also a question about some files whose headers state they are under the old 4-clause BSD license. It's not clear whether those files were supposed to be included in the GPL relicensing. Most of those files were in the [deleted libstd directory](https://github.com/grobian/html2text/commit/75df1127388799b51c7d89a47c8b25ab96253332) however two files with BSD license headers remain in the project today: [cmp_nocase.cpp](https://github.com/grobian/html2text/blob/master/cmp_nocase.cpp) and [sgml.h](https://github.com/grobian/html2text/blob/master/sgml.h).

**Comment by grobian** [comment]
The German response in my interpretation says that one4net (which I assume is GMRS Software GmbH) is ok with relicensing to GPL as long as they won't get any disadvantages as well as obligations.  This is as far as my understanding goes the same as you translated.  I'll dig up a bit of my email conversation with original authors, I believe they may contain hints towards if they can get disadvantages of re-licensing.
