### ISSUE TITLE
html2text-2.0.0: whimsical object code

### ISSUE THREAD

**Issue by estellnb** [grobian/html2text#54]
Hi, I have discovered a bug in html2text-2.0.0; for details look at https://bugs.mageia.org/show_bug.cgi?id=32044
Html2text-2.0.0 dumps core when invoked on the provided file, both with i586, amd64, Mageia 9 and OpenSuSE Leap 15.4.
The reason why I am asking is that I simply have no clue about how the x86 instructions shown for htmlparser_yylex could belong to Line 91 in HTMLControl.cpp, which obviously does the call to the isspace glibc function. I have had some look at the assembly of htmlparser_yylex that does the call (passed parameter value matches) but it does something rather weird, not what the source file says it should be doing. I have already suspected that there could be an issue with the compiler! I have decided to contact you, since you should know best what the C++ sources you have written should do. As far as I have tested with OpenSuSE Tumbleweed an html2text-2.1.1-1.3.x86_64 the error has gone away with newer versions. That does not mean the issue should not be investigated, however.

**Comment by grobian** [comment]
sounds like you're hit by https://github.com/grobian/html2text/commit/0e9734db13d1f0e398dcea59e55da7460b9faae4

On that note, 2.1.1 is out for a while...

**Comment by estellnb** [comment]
That patch explains well why later versions do not coredump and go on with processing. Nonetheless if you have a look at the gdb log you see that isspace is called with the following value:
hex(9739490) = '0x949ce2'
wchar_t is 32bit, as far as good, but if I examine the input file HSAHEC6K2, no such unicode character exists. The only non-ascii, utf-8 strings are: 
$       if ($("#toggle_star").html() == "&E2;&98;&86;") { $("#toggle_star").html("&starf;") }&0A;
$ 114&C2;&A0;bytes of <strong>Plain text</strong>&0A;
$ Created 1&C2;&A0;day, 9&C2;&A0;hours ago&0A;
$    &E2;&80;&94; expires in <strong>6 days</strong>&0A;
If you do not want to decode utf-8 by hand you can use python: 
codecs.decode(b'\xC2\xA0',encoding='utf-8') = '\xa0'
So the unicode characters in that file you can look for are:
U+2014 "em dash"
U+2606 "white star"
U+A0 "no break space"
, but no U+949ce2 - such a unicode character does not seem to exist (see also https://unicodeplus.com/search)

  Why the hell is "isspace(c)" called with a non-character value? Have you run html2text with Asan or Valgrind? Obviously that fix would just hide another issue here. Can you explain why the value fed into isspace comes directly from the stack (apparently a parameter value as it is the value below (address above) BP)? That is like a procedure calling isspace with its own parameter (must be the first parameter of that procedure as it appears last on the stack, C pushes params in reverse order).

**Comment by grobian** [comment]
If you really want to know why it acts like that, you'll have to check how the code uses it.  The comment in the commit I pointed you to before hits at it all, I believe.  The code is not using wchar_t or anything, and it has manual UTF-8 codepoint code.  It actually pushes an int out with all bytes from the codepoint.  One day, when I get the time, I will rip out the C++ legacy, and just turn it into proper code, but for now this patchwork will have to do.
