### ISSUE TITLE
configure.ac:16: error: Autoconf version 2.71 or higher is required

### ISSUE THREAD

**Issue by manfredsc** [grobian/html2text#60]
A lot of distros ship with quite old autotools, so you need to either ship
pre-configured config files, or you need to lower the requirements of autoconf to <= 2.69.

**Comment by grobian** [comment]
Is the release tarball not containing the generated files?

They were specifically removed because of https://github.com/grobian/html2text/issues/58 :/ it cannot be both.

**Comment by manfredsc** [comment]
I got the following error message:
```
#> ./configure
configure: loading site script /usr/share/site/x86_64-unknown-linux-gnu
configure: error: cannot find required auxiliary files: compile config.guess config.sub missing install-sh
```

**Comment by grobian** [comment]
yes, but you're using a git checkout, are you?

**Comment by manfredsc** [comment]
No, I used https://github.com/grobian/html2text/archive/refs/tags/v2.2.3.tar.gz

I see now that https://github.com/grobian/html2text/releases/download/v2.2.3/html2text-2.2.3.tar.gz
is different, so the tag and the release tarball are not identical, that is unexpected.

I just tested it, the release tarball is OK and builds fine.

Is there a possibility to make the tag and the release tarball identical? Otherwise, this is just
too confusing.
The tag tarball contains `PACKAGE_VERSION='2.2.2.9999_pre'`, while
the release tarball says `PACKAGE_VERSION='2.2.3'`, that is surprising, too.

**Comment by grobian** [comment]
That's an unfortunate artifact of git, even when I would commit the generated files, it would not save mtimes so you'll end up with all kinds of problems anyway.

The tag not containing the correct version is in a way correct, only the release-tarball is the official release, all the rest is not.

**Comment by manfredsc** [comment]
The unfortunate thing is, that the tag download gets redirected and contains
`content-disposition: attachment; filename=html2text-2.2.3.tar.gz
`
So it gets the exactly same name as the release tarball ...

**Comment by manfredsc** [comment]
What is the purpose of `AC_PREREQ([2.71])` ?
I changed it manually to `AC_PREREQ([2.69])` and everything went fine.
I did a
```
autoreconf -if
./configure
make
```
and I did not encounter any errors or warnings, using autoconf 2.69.
It would help a lot if requirements could be lowered to version 2.69.

**Comment by grobian** [comment]
What are you trying to do?  The release tarball doesn't require autoconf, does it?

**Comment by manfredsc** [comment]
So I could also install tag versions. Or will you do for each tag version also a release version, in future?
Up to 2.2.3, only tags were present.

**Comment by manfredsc** [comment]
OK then, so the change of AC_PREREQ is not needed. Thanks!
