### ISSUE TITLE
Can't configure

### ISSUE THREAD

**Issue by pkzc** [grobian/html2text#61]
peter@gygv ~/tmp/html2text-2.2.3
$ ./configure 
configure: error: cannot find required auxiliary files: compile config.guess config.sub missing install-sh

install-sh is present on the master branch, but the others are still missing.

The newest one I managed to compile is 2.1.1.

**Comment by grobian** [comment]
I fixed this post-2.2.3, you need to run `autoreconf -f -i`

**Comment by pkzc** [comment]
Thank you, the tarball works fine, somehow it did not occur to me to try it.

Unfortunately I don't know how to use autoreconf correctly, it starts off with a warning then winds up in undefined macro errors:
```
$ autoreconf -f -i .
configure.ac:20: warning: AC_LIB_PREPARE_PREFIX is m4_require'd but not m4_defun'd
m4/iconv.m4:16: AM_ICONV_LINKFLAGS_BODY is expanded from...
m4/iconv.m4:27: AM_ICONV_LINK is expanded from...
m4/iconv.m4:243: AM_ICONV is expanded from...
configure.ac:20: the top level
configure.ac:20: warning: AC_LIB_RPATH is m4_require'd but not m4_defun'd
m4/iconv.m4:16: AM_ICONV_LINKFLAGS_BODY is expanded from...
m4/iconv.m4:27: AM_ICONV_LINK is expanded from...
m4/iconv.m4:243: AM_ICONV is expanded from...
configure.ac:20: the top level
configure:3485: error: possibly undefined macro: AC_LIB_PREPARE_PREFIX
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure:3486: error: possibly undefined macro: AC_LIB_RPATH
configure:3491: error: possibly undefined macro: AC_LIB_LINKFLAGS_BODY
configure:4749: error: possibly undefined macro: AC_LIB_APPENDTOVAR
autoreconf: error: /usr/bin/autoconf failed with exit status: 1
```

**Comment by grobian** [comment]
That's why I checked in the configure file and such in the current code, because you need a lot of build tools with the correct version to run autoreconf.  In this case it's complaining about missing libiconv, I think.

**Comment by pkzc** [comment]
You must be right, but I stop here: I am on Fedora Linux, there is no libiconv, and it looks like glibc-gconv-extra should be used instead. But that's likely beyond me. After all, I was able to compile 2.2.3 from the tarball, the ISO8859-2 conversion didn't work in 2.0.0, and now I am happy to see it working, thanks again.
